# USE THE BASE IMAGE OF PYTHON
FROM  python:latest

# SET THE WORKING DIRECTORY
WORKDIR /app

# COPY THE REQUIREMENTS FILE
COPY reqirements.txt .

# INSTALL THE DEPENDENCIES
RUN pip install --no-cache-dir -r reqirements.txt

# EXPOSE THE PORT THE APP WILL RUN ON

EXPOSE 5000

# COMMAND TO RUN TEHE APP
CMD ["python"]
