version: "3.9"
services:
  mysql_db:
    image: mysql:latest    # use MYSQL 8.0 image
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root # set root password
      - MYSQL_DATABASE=test_db # create a test database
      - MYSQL_USER=test_user # create a test user
      - MYSQL_PASSWORD=test_password # set test user password
    ports:
      - "3306:3306" # expose port 3306
    volumes:
      - mysql_data:/var/lib/mysql # persist data in a named volume
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # initialize database with a script
  python_app:
    build:
      context: . # build the Dockerfile in the current directory
      dockerfile: dockerfile # specify the Dockerfile
    container_name: python_app
    depends_on:
      - mysql_db # wait for mysql_db to be ready
    environment:
      - DB_HOST=mysql_db # set the database host
      - DB_PORT=3306 # set the database port
      - DB_USER=test_user # set the database user
      - DB_PASSWORD=test_password # set the database password
      - DB_NAME=test_db # set the database name
    volumes:
      - ./scripts :/app # mount the app directory

volumes:
  mysql_data:
    driver: local # use local driver for the volume   